import 'package:diet_app/core/themes/theme_colors.dart';
import 'package:flutter/material.dart';

class LightTheme {
  ThemeData get theme => ThemeData(
        brightness: Brightness.light,
        primaryColor: const Color(0xff1B00D4),
        cardColor: const Color(0xffFFFFFF),
        hintColor: const Color(0xffB2B2B2),
        disabledColor: const Color(0xffBDBEC4),
        scaffoldBackgroundColor: const Color(0xffF5F5F5),
        canvasColor: const Color(0xffF8F9FE),
        dividerColor: const Color(0xffD1D5DB),
        iconTheme: const IconThemeData(
          color: Color(0xff3F4346),
        ),
        appBarTheme: const AppBarTheme(
          color: Color(0xffFEFEFE),
          foregroundColor: Color(0xff191919),
          elevation: 0.5,
        ),
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff1B00D4),
          inversePrimary: Color(0xffFB5058),
          onPrimary: Color(0xffF1F1F1),
          secondary: Color(0xffFDB63A),
          onSecondary: Color(0xffF1F1F1),
          error: Color(0xffF05252),
          onError: Color(0xffF1F1F1),
          background: Color(0xffF5F5F5),
          onBackground: Color(0xff191919),
          surface: Color(0xffFFFFFF),
          onSurfaceVariant: Color(0xff9E9E9E),
          onSurface: Color(0xff191919),
        ),
        extensions: const [
          ThemeColors(
            primary: Color(0xffEE4B67),
            cian: Color(0xff74CEE5),
            green: Color(0xff62CC86),
            red: Color(0xffEE3E3C),
            blue: Color(0xff5879A6),
            yellow: Color(0xffF8C86A),
            pink: Color(0xffFA6A9D),
            purple: Color(0xffBA93EA),
            orange: Color(0xffE96A4E),
            red50: Color(0xffFDE8E8),
            red75: Color(0xffF8B4B4),
            grey: Color(0xffF4F2F6),
          ),
        ],
        scrollbarTheme: const ScrollbarThemeData().copyWith(
          thickness: MaterialStateProperty.all(3.6),
        ),
        textTheme: const TextTheme(
          displayLarge: TextStyle(
            fontSize: 57.0,
            fontWeight: FontWeight.w400,
            letterSpacing: -0.25,
            height: 1.12,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          displayMedium: TextStyle(
            fontSize: 45.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.0,
            height: 1.16,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          displaySmall: TextStyle(
            fontSize: 36.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.0,
            height: 1.22,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          headlineLarge: TextStyle(
            fontSize: 32.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.0,
            height: 1.25,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          headlineMedium: TextStyle(
            fontSize: 26.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.0,
            height: 1.29,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          headlineSmall: TextStyle(
            fontSize: 24.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.0,
            height: 1.33,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          titleLarge: TextStyle(
            fontSize: 22.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.0,
            height: 1.27,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          titleMedium: TextStyle(
            fontSize: 16.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.15,
            height: 1.50,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          titleSmall: TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.1,
            height: 1.43,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          labelLarge: TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.1,
            height: 1.43,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          labelMedium: TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.w600,
            letterSpacing: 0.5,
            height: 1.33,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          labelSmall: TextStyle(
            fontSize: 11.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.5,
            height: 1.45,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          bodyLarge: TextStyle(
            fontSize: 21.0,
            fontWeight: FontWeight.w600,
            letterSpacing: 0.5,
            height: 1.50,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          bodyMedium: TextStyle(
            fontSize: 16.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.25,
            height: 1.43,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
          bodySmall: TextStyle(
            fontSize: 12.0,
            fontWeight: FontWeight.w400,
            letterSpacing: 0.4,
            height: 1.33,
            textBaseline: TextBaseline.alphabetic,
            leadingDistribution: TextLeadingDistribution.even,
            fontFamily: 'Quicksand',
          ),
        ).apply(
          bodyColor: const Color(0xff191919),
          displayColor: const Color(0xff191919),
        ),
      );
}
